### ISSUE TITLE
Published IDLE example failing with Python 3.9

### ISSUE THREAD

**Issue by JacobHenner** [bamthomas/aioimaplib#65] opened 2021-04-17 15:53 UTC
Using 0.8.0:

```
Traceback (most recent call last):
  File "/app/slack_responding/test.py", line 26, in <module>
    loop.run_until_complete(
  File "/usr/lib/python3.9/asyncio/base_events.py", line 642, in run_until_complete
    return future.result()
  File "/app/slack_responding/test.py", line 8, in wait_for_new_message
    await imap_client.wait_hello_from_server()
  File "/app/.venv/lib/python3.9/site-packages/aioimaplib/aioimaplib.py", line 694, in wait_hello_from_server
    await asyncio.wait_for(self.protocol.wait('AUTH|NONAUTH'), self.timeout)
  File "/usr/lib/python3.9/asyncio/tasks.py", line 481, in wait_for
    return fut.result()
  File "/app/.venv/lib/python3.9/site-packages/aioimaplib/aioimaplib.py", line 594, in wait
    with await self.state_condition:
TypeError: object Condition can't be used in 'await' expression
```

**Comment by bamthomas** [comment] 2021-04-17 16:33
duplicate of #64 I will release a 0.9 now please use this one

**Closed** 2021-04-18 13:50 UTC
